import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { Document, Packer, Paragraph, Table, TableRow, TableCell, TextRun, AlignmentType, BorderStyle } from 'docx';
import { saveAs } from 'file-saver'; // This might need installation if used on client, but we'll do it for server/client

export const exportToPDF = (data: any[], companyName: string, monthName: string, year: string) => {
  const doc = new jsPDF() as any;
  
  // Header
  doc.setFontSize(20);
  doc.setTextColor(124, 58, 237); // #7C3AED
  doc.text(companyName, 14, 20);
  
  doc.setFontSize(14);
  doc.setTextColor(15, 10, 30); // #0F0A1E
  doc.text(`Attendance Report - ${monthName} ${year}`, 14, 30);
  
  const tableData = data.map((item, index) => [
    item.employeeName,
    item.employeeEmail,
    item.date,
    new Date(item.checkInTime).toLocaleTimeString(),
    item.checkOutTime ? new Date(item.checkOutTime).toLocaleTimeString() : '-',
    item.status === 'checked-out' ? 'Complete' : 'Checked In'
  ]);

  doc.autoTable({
    startY: 40,
    head: [['Employee Name', 'Email', 'Date', 'Check-In', 'Check-Out', 'Status']],
    body: tableData,
    headStyles: { fillColor: [124, 58, 237] },
    alternateRowStyles: { fillColor: [250, 250, 255] },
  });

  const finalY = (doc as any).lastAutoTable.finalY || 40;
  doc.setFontSize(10);
  doc.text(`Total Present: ${data.length}`, 14, finalY + 10);
  doc.text(`Generated by Anvil Automation`, 14, finalY + 20);

  return doc.output('blob');
};

export const exportToExcel = (data: any[], companyName: string, monthName: string, year: string) => {
  const tableData = data.map(item => ({
    'Employee Name': item.employeeName,
    'Email': item.employeeEmail,
    'Date': item.date,
    'Check-In Time': new Date(item.checkInTime).toLocaleTimeString(),
    'Check-Out Time': item.checkOutTime ? new Date(item.checkOutTime).toLocaleTimeString() : '-',
    'Status': item.status === 'checked-out' ? 'Complete' : 'Checked In'
  }));

  const worksheet = XLSX.utils.json_to_sheet(tableData);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, 'Attendance');
  
  const excelBuffer = XLSX.write(workbook, { bookType: 'xlsx', type: 'array' });
  return new Blob([excelBuffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
};

export const exportToWord = async (data: any[], companyName: string, monthName: string, year: string) => {
  const doc = new Document({
    sections: [{
      properties: {},
      children: [
        new Paragraph({
          children: [
            new TextRun({
              text: companyName,
              bold: true,
              size: 40,
              color: '7C3AED',
            }),
          ],
          alignment: AlignmentType.CENTER,
        }),
        new Paragraph({
          children: [
            new TextRun({
              text: `Attendance Report - ${monthName} ${year}`,
              bold: true,
              size: 28,
            }),
          ],
          alignment: AlignmentType.CENTER,
          spacing: { after: 400 },
        }),
        new Table({
          rows: [
            new TableRow({
              children: [
                new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: 'Name', bold: true })] })] }),
                new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: 'Email', bold: true })] })] }),
                new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: 'Date', bold: true })] })] }),
                new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: 'Check-In', bold: true })] })] }),
                new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: 'Check-Out', bold: true })] })] }),
                new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: 'Status', bold: true })] })] }),
              ],
            }),
            ...data.map(item => new TableRow({
              children: [
                new TableCell({ children: [new Paragraph(item.employeeName)] }),
                new TableCell({ children: [new Paragraph(item.employeeEmail)] }),
                new TableCell({ children: [new Paragraph(item.date)] }),
                new TableCell({ children: [new Paragraph(new Date(item.checkInTime).toLocaleTimeString())] }),
                new TableCell({ children: [new Paragraph(item.checkOutTime ? new Date(item.checkOutTime).toLocaleTimeString() : '-')] }),
                new TableCell({ children: [new Paragraph(item.status === 'checked-out' ? 'Complete' : 'Checked In')] }),
              ],
            })),
          ],
        }),
        new Paragraph({
          children: [
            new TextRun({
              text: `\nTotal Present: ${data.length}`,
              bold: true,
            }),
          ],
          spacing: { before: 400 },
        }),
        new Paragraph({
          children: [
            new TextRun({
              text: 'Generated by Anvil Automation',
              italics: true,
            }),
          ],
          spacing: { before: 200 },
        }),
      ],
    }],
  });

  return Packer.toBlob(doc);
};
